package com.microsoft.azure.cosmosdb.kafka.connect.sink;

import org.apache.kafka.connect.runtime.SinkConnectorConfig;
import org.junit.Test;

import java.util.Map;

import static org.junit.Assert.fail;

public class SinkConnectorTest {
    @Test
    public void ensureGeneratedSettingsPassValidation() {
        for (Map<String, String> settingMap : new CosmosDBSinkConnector().taskConfigs(12)) {
            try{
                SinkConnectorConfig.validate(settingMap);
            } catch (Exception e){
                fail("Unable to validate settings generated by `taskConfigs`.");
            }
        }
    }
}
